"""updated clients table

Revision ID: d0c4aeb1b49f
Revises: 76ce6106fb26
Create Date: 2026-05-05 17:39:31.359413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0c4aeb1b49f'
down_revision: Union[str, Sequence[str], None] = '76ce6106fb26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('full_name', sa.String(length=510), nullable=False))
    op.drop_column('clients', 'last_name')
    op.drop_column('clients', 'first_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('first_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('clients', sa.Column('last_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('clients', 'full_name')
    # ### end Alembic commands ###
